client_config_backend: settings
client_config:
  client_id: YOUR GOOGLE CLIENT ID
  client_secret: YOUR GOOGLE CLIENT SECRET
save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json
get_refresh_token: True
